
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin79
    url: jdbc:postgresql://localhost:5432/internship
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


